### ISSUE TITLE
distribution abstract is kinda sucky

### ISSUE THREAD

**Issue by tobyink** [jmacdotorg/sweat#4]
https://metacpan.org/source/JMAC/Sweat-201912110/META.json

```
"abstract" : "Library for the `sweat` command-line program",
```

It doesn't say what the `sweat` command-line program does, and it makes it sound like the `sweat` command-line program is some third-party thing that isn't included.

The description for the command line program is "a chatty, distracting, and flexible workout timer" and that would make a much better distribution abstract.

**Comment by jmacdotorg** [comment]
Acknowledged and fixed. Thank you very much!
